### ISSUE TITLE
SyntaxError: missing ; before statement

### ISSUE THREAD

**Issue by jboulmal** [zorglub42/OSA#3]
Hi, 
First of all Thank you for this great tool!
I got that issue while adding new entry `Services` using docker container.
![osa](https://cloud.githubusercontent.com/assets/15377466/21433319/b1f9c78a-c86f-11e6-8507-31f393f8a1e3.png)
Thanks

**Comment by zorglub42** [comment]
Hi jboulmal,

Thanks for using OSA: my pleasure!

I've just tried to re-generate a docker image right now (12/22/16 6PM30) ans starts it with docker run --net=host -d zorglub42:osa
Every thing is working fine on my side.... I guess it gona be tricky to fix your issue :(
Anyway...
Can you try the following:
- connect the container itself (docker exec -it container-id bash)
- go to OSA webapp files: cd /var/www/local/main/ApplianceManager/js/src
- swith to usage of plain js files intead of minimized ones :  ./use src
- and then, reload the app in your browser and retry to publish your service.
If an error occurs we should have more details on the real place of this error in sources ;)

**Comment by jboulmal** [comment]
Hi zorglub,

I'm not using docker image of OSA, I followed up the installation instructions for ubuntu 14.10.
Instead, the backend service I point to is a docker container on my localhost.
I fixed this issue by restarting installation all over, this issue happens once in while.

Thanks for the help!

**Comment by jboulmal** [comment]
Hi again,
The problem happens mainly when I want to edit previously created services.

**Comment by zorglub42** [comment]
Ok,

So I'll send you my email address via sbecot for the next time to investigate and I close this issue.
Enjoy

**Comment by zorglub42** [comment]
Salut,
Je vais essyer de mon coté.J'ai vu ds les developper tools du screenshot de l'issue github qu'un http 400 s'etait produit sur le post qui a lieu a la sauvegarde. Je pense que la "vrai" erreur est la et qu'ensuite il y en a une 2eme au niveau de l'interception de cette erreur au niveau javascript.
Zorg




-------- Message d'origine --------De : jboulmal <notifications@github.com> Date : 23/12/2016  10:56  (GMT+01:00) À : zorglub42/OSA <OSA@noreply.github.com> Cc : zorglub42 <contact@zorglub42.fr>, Comment <comment@noreply.github.com> Objet : Re: [zorglub42/OSA] SyntaxError: missing ; before statement (#3) 
Hi again,

The problem happens mainly when I want to edit previously created services.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zorglub42/OSA","title":"zorglub42/OSA","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/zorglub42/OSA"}},"updates":{"snippets":[{"icon":"PERSON","message":"@jboulmal in #3: Hi again,\r\nThe problem happens mainly when I want to edit previously created services."}],"action":{"name":"View Issue","url":"https://github.com/zorglub42/OSA/issues/3#issuecomment-268965879"}}}

**Comment by jboulmal** [comment]
Merci,

N'hésite pas à me demander plus de détails.:-)

cordialement,
Jamal
